name: Emojify
version: ${project.version}
main: org.technicfox.emojify.Emojify
api-version: '1.21'
author: TechnicFox
description: Panel for emojis
commands:
  emojis:
    description: Panel for emojis
    usage: /emoji
    aliases: [emo, em]