name: Emojify
version: 1.0
main: org.technicfox.emojify.Emojify
api-version: '1.21'
author: TechnicFox
description: Panel for emojis
commands:
  emoji:
    description: Panel for emojis
    usage: /emoji
    aliases: [emo, em]